pipeline:
    docker:
        repo: sierrasoftworks/ghost
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
            - "go"
        username: "${DOCKER_USERNAME}"
        password: "${DOCKER_PASSWORD}"
        email: "${DOCKER_EMAIL}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"